export type Language = 'en' | 'ar'

const en = {
  overview: 'Overview', myTeam: 'My team', activity: 'Activity', settings: 'Settings', manager: 'Manager', teamLead: 'Team lead', teamManagement: 'TEAM MANAGEMENT', headline: 'Your team, at a glance.', subhead: 'Track performance, celebrate progress, and keep every conversation moving.', export: 'Export', addMember: 'Add member', teamMembers: 'Team members', clickMember: 'Click a member to view their profile and transaction history.', sendTo: 'Send to Malak', shareUnsupported: 'File sharing is not available in this browser. Open this page on a mobile device or a browser that supports file sharing.', activeMonth: 'Active this month', performanceRate: 'Performance rate', acrossTeam: 'Across your team', teamAverage: 'Team average', totalPoints: 'Total points', points: 'points', updates: 'updates', newMember: 'NEW TEAM MEMBER', addPerson: 'Add a person to your team', fullName: 'Full name', namePlaceholder: 'e.g. Kirolos', cancel: 'Cancel', back: 'Back to team', memberProfile: 'MEMBER PROFILE', memberSince: 'Team member since', transactionHistory: 'Transaction history', transactionCopy: 'Every saved evaluation. Undo removes it from the member and export.', noTransactions: 'No transactions recorded yet.', undo: 'Undo', edit: 'Edit', deleteMember: 'Delete member', newEvaluation: 'NEW EVALUATION', editEvaluation: 'EDIT EVALUATION', logUpdate: 'Evaluate member', actionStatus: 'Action status', selectStatus: 'Select an action status', title: 'Title', titlePlaceholder: 'Give this evaluation a title', customTitle: 'Custom title', details: 'Details', detailsPlaceholder: 'Add useful context or excuse reason...', pointChange: 'Point change', date: 'Task date', save: 'Save evaluation', saveChanges: 'Save changes', evaluationUndone: 'Evaluation undone.', confirmDelete: 'Are you sure?', confirmTransaction: 'This evaluation will be permanently removed and excluded from exports.', confirmMember: 'This member will be hidden from the dashboard and excluded from exports.', delete: 'Delete', completed: 'Completed', excuse: 'Excuse', else: 'Else', report: 'Report', memberDeleted: 'Member deleted', language: 'العربية', leaderTitle: 'Team Pulse evaluation', shared: 'Shared with you by Team Pulse.'
}

const ar: typeof en = {
  overview: 'نظرة عامة', myTeam: 'فريقي', activity: 'النشاط', settings: 'الإعدادات', manager: 'المدير', teamLead: 'قائد الفريق', teamManagement: 'إدارة الفريق', headline: 'فريقك في لمحة.', subhead: 'تابع الأداء، احتفل بالتقدم، وحافظ على كل محادثة فعالة.', export: 'تصدير', addMember: 'إضافة عضو', teamMembers: 'أعضاء الفريق', clickMember: 'اضغط على عضو لعرض ملفه وسجل معاملاته.', sendTo: 'إرسال إلى ملاك', shareUnsupported: 'مشاركة الملفات غير متاحة في هذا المتصفح. افتح الصفحة على هاتف أو متصفح يدعم مشاركة الملفات.', activeMonth: 'نشط هذا الشهر', performanceRate: 'معدل الأداء', acrossTeam: 'عبر فريقك', teamAverage: 'متوسط الفريق', totalPoints: 'إجمالي النقاط', points: 'نقاط', updates: 'تحديثات', newMember: 'عضو فريق جديد', addPerson: 'أضف شخصا إلى فريقك', fullName: 'الاسم بالكامل', namePlaceholder: 'مثال: كيرلس', cancel: 'إلغاء', back: 'العودة للفريق', memberProfile: 'ملف العضو', memberSince: 'عضو بالفريق منذ', transactionHistory: 'سجل المعاملات', transactionCopy: 'كل التقييمات المحفوظة. التراجع يحذفها من العضو والتصدير.', noTransactions: 'لا توجد معاملات مسجلة بعد.', undo: 'تراجع', edit: 'تعديل', deleteMember: 'حذف العضو', newEvaluation: 'تقييم جديد', editEvaluation: 'تعديل التقييم', logUpdate: 'تقييم العضو', actionStatus: 'حالة الإجراء', selectStatus: 'اختر حالة الإجراء', title: 'العنوان', titlePlaceholder: 'أضف عنوانا للتقييم', customTitle: 'عنوان مخصص', details: 'التفاصيل', detailsPlaceholder: 'أضف سياقا مفيدا أو سبب العذر...', pointChange: 'تغيير النقاط', date: 'تاريخ المهمة', save: 'حفظ التقييم', saveChanges: 'حفظ التعديلات', evaluationUndone: 'تم التراجع عن التقييم.', confirmDelete: 'هل أنت متأكد؟', confirmTransaction: 'سيتم حذف هذا التقييم نهائيا واستبعاده من التصدير.', confirmMember: 'سيتم إخفاء هذا العضو من لوحة التحكم واستبعاده من التصدير.', delete: 'حذف', completed: 'مكتمل', excuse: 'عذر', else: 'أخرى', report: 'تقرير', memberDeleted: 'تم حذف العضو', language: 'English', leaderTitle: 'تقييم فريق Pulse', shared: 'تمت المشاركة معك عبر Pulse.'
}

export const messages = { en, ar }
export type MessageKey = keyof typeof en
